#!/usr/bin/env bash
# generate_uninstall_plan.sh — render the three-section decommission plan.
#
# Inputs (env vars, set by the Horus pipeline):
#   HELM_RELEASE       e.g. "nginx-ingress"
#   HELM_NAMESPACE     e.g. "ingress-nginx"
#   NGINX_LB_IP        e.g. "34.x.x.x"
#   GCP_PROJECT        e.g. "awoo-prod"
#   REPORT_DIR         absolute path of docs/reports/traefik-controller-decommission/<date>/
#
# Output:
#   $REPORT_DIR/plan.md       — operator-readable plan
#   $REPORT_DIR/commands.sh   — copy-paste-ready bash (never auto-executed)
set -euo pipefail

: "${HELM_RELEASE:?HELM_RELEASE required}"
: "${HELM_NAMESPACE:?HELM_NAMESPACE required}"
: "${NGINX_LB_IP:?NGINX_LB_IP required (use <TODO:lb-ip> if unknown)}"
: "${GCP_PROJECT:?GCP_PROJECT required (use <TODO:gcp-project> if unknown)}"
: "${REPORT_DIR:?REPORT_DIR required}"

mkdir -p "$REPORT_DIR"

PLAN="$REPORT_DIR/plan.md"
COMMANDS="$REPORT_DIR/commands.sh"

cat > "$PLAN" <<EOF
# nginx-ingress Decommission Plan

**Generated**: $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Helm release**: \`$HELM_RELEASE\` in namespace \`$HELM_NAMESPACE\`
**LB IP**: \`$NGINX_LB_IP\`
**GCP project**: \`$GCP_PROJECT\`

This plan is **printed only**. Run \`commands.sh\` block-by-block; do not
chain blocks. After each block verify with \`kubectl\` / \`helm\` /
\`gcloud\` that the previous step landed before continuing.

---

## 4a. Helm Uninstall

\`\`\`bash
helm status $HELM_RELEASE -n $HELM_NAMESPACE
helm get values $HELM_RELEASE -n $HELM_NAMESPACE -o yaml \\
  > $REPORT_DIR/nginx-values-snapshot.yaml
helm uninstall $HELM_RELEASE -n $HELM_NAMESPACE --wait
kubectl get all -n $HELM_NAMESPACE
# Only delete the namespace once the previous command returns 'No resources found'
kubectl delete namespace $HELM_NAMESPACE
\`\`\`

## 4b. LB IP Release (GKE / GCP)

\`\`\`bash
gcloud compute addresses list --project $GCP_PROJECT \\
  --filter="address=$NGINX_LB_IP"
gcloud compute forwarding-rules list --project $GCP_PROJECT \\
  --filter="IPAddress=$NGINX_LB_IP"
# After confirming no forwarding rule references the IP:
# gcloud compute addresses delete <address-name> --region <region> --project $GCP_PROJECT
\`\`\`

## 4c. IAM Cleanup

\`\`\`bash
gcloud iam service-accounts list --project $GCP_PROJECT \\
  --filter="email~ingress-nginx"
# For each candidate SA, list bindings then remove them and the SA:
# gcloud projects get-iam-policy $GCP_PROJECT \\
#   --flatten="bindings[].members" \\
#   --filter="bindings.members:serviceAccount:<sa-email>"
\`\`\`

---

Rollback: re-install the chart using the values snapshot captured in 4a:
\`\`\`bash
helm install $HELM_RELEASE ingress-nginx/ingress-nginx \\
  --namespace $HELM_NAMESPACE --create-namespace \\
  --values $REPORT_DIR/nginx-values-snapshot.yaml
\`\`\`
EOF

cat > "$COMMANDS" <<EOF
#!/usr/bin/env bash
# Generated by traefik-controller-decommission skill on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# THIS SCRIPT IS NOT AUTO-EXECUTED. Read every block, then run by hand.
set -euo pipefail

REPORT_DIR="$REPORT_DIR"

# ---- 4a. Helm uninstall ----
helm status $HELM_RELEASE -n $HELM_NAMESPACE
helm get values $HELM_RELEASE -n $HELM_NAMESPACE -o yaml \\
  > "\$REPORT_DIR/nginx-values-snapshot.yaml"
helm uninstall $HELM_RELEASE -n $HELM_NAMESPACE --wait
kubectl get all -n $HELM_NAMESPACE
# kubectl delete namespace $HELM_NAMESPACE   # uncomment after confirming empty

# ---- 4b. LB IP release ----
gcloud compute addresses list --project $GCP_PROJECT --filter="address=$NGINX_LB_IP"
gcloud compute forwarding-rules list --project $GCP_PROJECT --filter="IPAddress=$NGINX_LB_IP"
# gcloud compute addresses delete <address-name> --region <region> --project $GCP_PROJECT

# ---- 4c. IAM cleanup ----
gcloud iam service-accounts list --project $GCP_PROJECT --filter="email~ingress-nginx"
# (per-SA cleanup commands — see plan.md)
EOF

chmod +x "$COMMANDS"

echo "[generate_uninstall_plan] wrote $PLAN and $COMMANDS" >&2
