#!/usr/bin/env bash
# generate_decommission_plan.sh — render the GitOps decommission plan.
#
# Replaces the v1.0.0 helm-uninstall plan. The GitOps flow is:
#   1. Archive the Kustomize module → ArgoCD prunes resources
#   2. Disable + delete the ArgoCD Application
#   3. Optional LB IP / IAM cleanup
#
# Inputs (env vars):
#   NGINX_MODULE          e.g. "common.ingress-nginx"
#   ARGOCD_APP_MANIFESTS  comma-separated list of paths
#   NGINX_NAMESPACE       e.g. "ingress-nginx"
#   NGINX_LB_IP           e.g. "34.x.x.x" or "<TODO:lb-ip>"
#   GCP_PROJECT           e.g. "awoo-prod" or "<TODO:gcp-project>"
#   REPORT_DIR            absolute path to docs/reports/.../<date>/
#   SKIP_LB_CLEANUP       "1" to skip section 5c
#
# Output:
#   $REPORT_DIR/plan.md       — operator-readable plan
#   $REPORT_DIR/commands.sh   — copy-paste-ready bash
set -euo pipefail

: "${NGINX_MODULE:?required}"
: "${ARGOCD_APP_MANIFESTS:?required}"
: "${NGINX_NAMESPACE:?required}"
: "${NGINX_LB_IP:?required}"
: "${GCP_PROJECT:?required}"
: "${REPORT_DIR:?required}"
SKIP_LB_CLEANUP="${SKIP_LB_CLEANUP:-0}"

mkdir -p "$REPORT_DIR"
PLAN="$REPORT_DIR/plan.md"
COMMANDS="$REPORT_DIR/commands.sh"

# Render apps list (one per line for plan.md, comma-joined for commands.sh)
APPS_PIPE=$(echo "$ARGOCD_APP_MANIFESTS" | tr ',' '\n')

cat > "$PLAN" <<EOF
# ingress-nginx Decommission Plan (GitOps)

**Generated**: $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Module**: \`$NGINX_MODULE\`
**Namespace**: \`$NGINX_NAMESPACE\`
**LB IP**: \`$NGINX_LB_IP\`
**GCP project**: \`$GCP_PROJECT\`
**ArgoCD Apps**:
$(echo "$APPS_PIPE" | sed 's/^/- `/' | sed 's/$/`/')

This plan is **printed only**. Run \`commands.sh\` block-by-block;
do not chain blocks. After each block, verify with the suggested
\`kubectl\` commands before continuing. ArgoCD performs the actual
resource removal via its pruner — no \`helm uninstall\` is needed.

---

## 5a. Archive the Kustomize module

\`\`\`bash
git checkout main && git pull
git mv $NGINX_MODULE archive/
git commit -m "chore(ingress-nginx): archive controller module for decommission"
git push
\`\`\`

After this commit lands, ArgoCD will see the deleted manifests on its
next sync and start pruning the live resources.

## 5b. Disable + delete the ArgoCD Application

\`\`\`bash
# Disable auto-sync (prevents ArgoCD from recreating the module before prune):
$(for m in $APPS_PIPE; do
  app=$(basename "$m" .yaml)
  echo "kubectl patch application $NGINX_NAMESPACE-\$ENV-$app -n argocd --type merge \\"
  echo "  -p '{\"spec\":{\"syncPolicy\":{\"automated\":null}}}'"
done)

# Trigger explicit prune:
for env in dev stg prd; do
  kubectl patch application $NGINX_NAMESPACE-\$env -n argocd --type merge \\
    -p '{"operation":{"sync":{"prune":true,"force":true}}}'
done

# Wait for prune to finish, then delete the Application manifests:
$(echo "$APPS_PIPE" | sed 's|^|kubectl delete -f |')

# Verify zero resources remain
kubectl get all -n $NGINX_NAMESPACE
# Only after the above is empty:
kubectl delete namespace $NGINX_NAMESPACE
\`\`\`

EOF

if [[ "$SKIP_LB_CLEANUP" != "1" ]]; then
cat >> "$PLAN" <<EOF
## 5c. (Optional) LB IP release + IAM cleanup

\`\`\`bash
gcloud compute addresses list --project $GCP_PROJECT \\
  --filter="address=$NGINX_LB_IP"
gcloud compute forwarding-rules list --project $GCP_PROJECT \\
  --filter="IPAddress=$NGINX_LB_IP"
# After confirming no forwarding rule references the IP:
# gcloud compute addresses delete <address-name> --region <region> --project $GCP_PROJECT

gcloud iam service-accounts list --project $GCP_PROJECT \\
  --filter="email~ingress-nginx"
# Then per-SA: list bindings → remove → delete SA
\`\`\`

EOF
fi

cat >> "$PLAN" <<EOF
---

## Rollback

The archive is recoverable until the next \`archive/\` cleanup:

\`\`\`bash
git mv archive/$(basename $NGINX_MODULE) $NGINX_MODULE
git commit -m "revert: restore ingress-nginx controller module"
git push
# Reapply the ArgoCD Applications:
$(echo "$APPS_PIPE" | sed 's|^|kubectl apply -f |')
\`\`\`
EOF

cat > "$COMMANDS" <<EOF
#!/usr/bin/env bash
# Generated by traefik-controller-decommission skill on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# THIS SCRIPT IS NOT AUTO-EXECUTED. Read every block, then run by hand.
set -euo pipefail

# ---- 5a. Archive the Kustomize module ----
git checkout main && git pull
git mv $NGINX_MODULE archive/
git commit -m "chore(ingress-nginx): archive controller module for decommission"
git push

# ---- 5b. ArgoCD disable + delete ----
# (paste from plan.md — env-specific app name patches; commands depend on
#  the operator's actual ArgoCD Application naming convention)

# ---- Verify ----
kubectl get all -n $NGINX_NAMESPACE
# kubectl delete namespace $NGINX_NAMESPACE   # only after empty
EOF

if [[ "$SKIP_LB_CLEANUP" != "1" ]]; then
cat >> "$COMMANDS" <<EOF

# ---- 5c. (Optional) LB IP / IAM cleanup ----
gcloud compute addresses list --project $GCP_PROJECT --filter="address=$NGINX_LB_IP"
gcloud compute forwarding-rules list --project $GCP_PROJECT --filter="IPAddress=$NGINX_LB_IP"
# gcloud compute addresses delete <address-name> --region <region> --project $GCP_PROJECT
gcloud iam service-accounts list --project $GCP_PROJECT --filter="email~ingress-nginx"
EOF
fi

chmod +x "$COMMANDS"
echo "[generate_decommission_plan] wrote $PLAN and $COMMANDS" >&2
