#!/usr/bin/env bash
# render_release_artifact.sh — aggregate release-validate phases into a
# single Markdown artifact suitable for `gh release create --notes-file`.
#
# Inputs (env vars):
#   VERSION         — current VERSION file content (e.g. "1.14.0")
#   FIXTURES_JSON   — output of run_all_fixtures.sh
#   PORTABILITY_JSON — output of check_shell_portability.sh
#   OUTPUT          — absolute path to write the .md file
#
# Output:
#   $OUTPUT — Markdown release artifact
#   stdout — a one-line verdict summary
#
# Exit codes:
#   0   artifact written, overall verdict PASS or WARN
#   1   any phase verdict FAIL → release blocked
set -euo pipefail

: "${VERSION:?VERSION required}"
: "${FIXTURES_JSON:?FIXTURES_JSON required (path)}"
: "${PORTABILITY_JSON:?PORTABILITY_JSON required (path)}"
: "${OUTPUT:?OUTPUT required}"

command -v jq >/dev/null 2>&1 || { echo "jq not on PATH" >&2; exit 2; }

# Parse aggregated phase outputs
FIX_VERDICT=$(jq -r '.verdict' "$FIXTURES_JSON")
FIX_TOTAL_PASS=$(jq -r '.totalPass' "$FIXTURES_JSON")
FIX_TOTAL_FAIL=$(jq -r '.totalFail' "$FIXTURES_JSON")
FIX_SUITES=$(jq -r '.totalSuites' "$FIXTURES_JSON")

PORT_VERDICT=$(jq -r '.verdict' "$PORTABILITY_JSON")
PORT_SCANNED=$(jq -r '.scanned' "$PORTABILITY_JSON")
PORT_ERRORS=$(jq -r '.errors' "$PORTABILITY_JSON")
PORT_WARNINGS=$(jq -r '.warnings' "$PORTABILITY_JSON")

# Compose overall verdict. FAIL > WARN > OK; takes the worst.
OVERALL="PASS"
[[ "$PORT_VERDICT" == "WARN" || "$FIX_VERDICT" == "WARN" ]] && OVERALL="WARN"
[[ "$PORT_VERDICT" == "FAIL" || "$FIX_VERDICT" == "FAIL" ]] && OVERALL="FAIL"

# Build the per-suite table
SUITE_ROWS=$(jq -r '.suites[] | "| \(.name) | \(.pass) | \(.fail) | \(.verdict) |"' "$FIXTURES_JSON")
PORT_ISSUE_ROWS=$(jq -r '.issues[]? | "| \(.file):\(.line) | \(.severity) | \(.rule) |"' "$PORTABILITY_JSON" || echo "| _none_ | | |")

mkdir -p "$(dirname "$OUTPUT")"

cat > "$OUTPUT" <<EOF
# Release Check — v${VERSION}

**Generated**: $(date -u +%Y-%m-%dT%H:%M:%SZ)
**Overall verdict**: **${OVERALL}**

## Summary

| Phase | Verdict | Detail |
|---|---|---|
| 4. Fixture suites | ${FIX_VERDICT} | ${FIX_TOTAL_PASS} PASS / ${FIX_TOTAL_FAIL} FAIL across ${FIX_SUITES} suites |
| 5. Shell portability | ${PORT_VERDICT} | ${PORT_SCANNED} scripts scanned, ${PORT_ERRORS} errors, ${PORT_WARNINGS} warnings |

## Phase 4 — Skill fixture suites

| Suite | PASS | FAIL | Verdict |
|---|---|---|---|
${SUITE_ROWS}

## Phase 5 — Shell portability static checks

Scanned: ${PORT_SCANNED} \`.sh\` files under \`skills/\` and \`scripts/\`.

Rules:
1. Portable shebang (\`#!/usr/bin/env bash\`)
2. No \`declare -A\` (bash 3.2 incompatible)
3. No \`mapfile\`/\`readarray\` (bash 4+)
4. No \`sed -i\` without backup suffix (BSD vs GNU divergence)
5. No \`readlink\` with the \`-f\` flag (BSD lacks it; use \`cd && pwd\` instead)

| Location | Severity | Rule |
|---|---|---|
${PORT_ISSUE_ROWS}

## How to interpret

- **PASS** — release is green; safe to \`pnpm release\`.
- **WARN** — release is acceptable but has portability or coverage gaps. Review the issue list; consider fixing in a follow-up.
- **FAIL** — at least one fixture suite errored or a shell script has a hard-incompatibility. Do NOT release.

## Next steps

\`\`\`bash
# If verdict is PASS or WARN:
pnpm release   # triggers GitHub Actions release.yml

# If verdict is FAIL:
# fix the failing suite / portability issue, then re-run:
bash skills/release-validate/scripts/run_all_fixtures.sh
bash skills/release-validate/scripts/check_shell_portability.sh .
\`\`\`

---

_Generated by \`release-validate\` skill v2.0.0. This artifact is suitable
for the \`gh release create --notes-file\` body, or as the npm publish
README excerpt._
EOF

# Print a one-line summary suitable for CI logs
echo "release-validate v${VERSION}: ${OVERALL} (fixtures=${FIX_VERDICT}, portability=${PORT_VERDICT})"

[[ "$OVERALL" == "FAIL" ]] && exit 1 || exit 0
